v1.0.2: Add metadata output
bitnami-labs/readme-generator-for-helm pull request #5
Opened 2021-07-16 08:56 UTC by migruiz4

**Description of the change**

Modifies the Readme-generator-for-helm to also generate a Json file containing the `values.yaml` metadata.

Additionally, adds a Dockerfile to create a docker image for the readme-generator.

**Checklist**

- [ ] Version bumped in `package.json` and `package-lock.json` according to [semver](http://semver.org/).
- [ ] New features are documented in the README.md
- [ ] New features contain a new test at the `tests` folder
- [ ] All tests pass running `npm test`

2021-07-16 10:02 UTC, miguelaeh requested changes
Thank you very much for adding this new feature!
Please take a look at the comments

2021-07-16 10:02 UTC, miguelaeh commented on lib/parser.js
> +function generateMetadataObject(sections) {
Please add some comments, at least about what this receives and what it returns, it will be really helpful in the future for other people.

2021-07-16 10:02 UTC, miguelaeh commented on lib/render.js
> +  values.forEach(function(value){
Please add a comment about what this loop is doing

2021-07-27 15:22 UTC, migruiz4 commented on index.js
> -  if (!readmeFilePath) {
Done

2021-07-28 12:10 UTC, migruiz4 commented
Hi @miguelaeh,

Additionally, fixed some linting issues and made some changes to the method used to detect the variable types.

Please let me know if you have any other suggestions.

2021-07-29 09:06 UTC, miguelaeh commented on tests/basic.test.js
> +  // Run readme gnerator with the test files
typo here

2021-07-29 09:16 UTC, miguelaeh approved these changes
Thank you for the changes!
LGTM!

2021-07-29 10:33 UTC, migruiz4 commented
Tested that the schema generated is correct using:
```bash
# workdir: charts/bitnami
for d in *; do
  if [ -f "${d}/README.md" ]; then
      readme-generator -v "${d}/values.yaml" -m "${d}/values.schema.json" > /dev/null
      helm template $d > /dev/null
  fi
done
```

2021-07-29 10:44 UTC, merged